name: Deploy CI

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Increment versionCode
        uses: chkfung/android-version-actions@v1.1
        with: 
          gradlePath: app/build.gradle
          versionCode: ${{ github.run_number }}

      - name: Build keystore file
        run: |
          echo '${{ secrets.RELEASE_KEYSTORE }}' | base64 -di > awakedebug.keystore
        
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          
      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
            name: app
            path: app/build/outputs/apk/release/app-release.apk
            
      - name: Deploy to Google Play Alpha
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.afzaln.awakedebug
          releaseFiles: app/build/outputs/apk/release/app-release.apk
          track: alpha
          whatsNewDirectory: whatsnew/
